import type { Metadata } from "next";
import Link from "next/link";
import { LegalDocument } from "@/components/LegalDocument";

export const metadata: Metadata = { title: "Privacy Policy — JusCAD", description: "How JusCAD collects, uses, stores, and protects personal information." };
export default function PrivacyPage() {
  return <LegalDocument eyebrow="Legal / 01" title="Privacy Policy" summary="This policy explains what information JusCAD handles, why we handle it, and the choices available to you.">
    <h2>1. Who we are</h2><p>JusCAD develops cognitive engineering software. For privacy questions, contact <a href="mailto:enquire@juscad.com">enquire@juscad.com</a> or write to JusCAD, Desai Sethi School of Entrepreneurship, Indian Institute of Technology Bombay, Powai, Mumbai, Maharashtra 400076, India.</p>
    <h2>2. Information we collect</h2><p>We collect account information such as your name, email address, authentication identifiers, and sign-in provider. If you submit a beta, contact, or job application form, we collect the information you enter. We also receive limited technical information needed for security, fraud prevention, and measuring site performance.</p>
    <h2>3. How we use information</h2><p>We use information to create and secure accounts, respond to messages, evaluate beta and job applications, operate the website, publish requested content, prevent abuse, measure reliability, comply with law, and improve JusCAD. We do not sell personal information.</p>
    <h2>4. Services that process information</h2><p>Supabase provides authentication, database, and media storage. Vercel hosts the website and supplies anonymous Web Analytics and Speed Insights. Resend delivers transactional email. Google Workspace stores the temporary submission spreadsheet mirror and supports Google sign-in. Cloudflare Turnstile helps detect automated abuse. Each provider processes information under its own terms and security controls.</p>
    <h2>5. Cookies and analytics</h2><p>Essential authentication cookies keep you signed in and are required for account features. Vercel Web Analytics is configured without advertising cookies and is not used to build cross-site profiles. We do not place marketing cookies.</p>
    <h2>6. Retention</h2><p>Account information remains until you delete your account or it is no longer needed. Beta and contact submissions are retained for up to 24 months; job applications for up to 12 months; salted anti-abuse hashes for up to 24 hours. Delivery records and backups may persist briefly for security, continuity, or legal obligations.</p>
    <h2>7. Sharing and international processing</h2><p>We share information only with service providers, professional advisers, authorities when legally required, or a successor involved in a corporate transaction. Providers may process information outside India with contractual and technical safeguards appropriate to the service.</p>
    <h2>8. Your choices and rights</h2><p>You may update your profile, change your email, sign out, or delete a normal-user account from <Link href="/settings">Settings</Link>. You may also ask to access, correct, or erase information by emailing us. Some records may be retained where law or legitimate security needs require it.</p>
    <h2>9. Security and children</h2><p>We use access controls, row-level database policies, encrypted transport, and restricted server credentials. No system is completely secure. JusCAD is not directed to children under 13; users under the age required to consent in their country should use the service only with a parent or guardian.</p>
    <h2>10. Changes</h2><p>We may update this policy as the product changes. Material revisions will be identified by a new effective date and, where appropriate, an account notice.</p>
  </LegalDocument>;
}
